# Global settings
global:
  appName: "shopnow-frontend"
  namespace: "shopnow"
  enabledComponents:
    configmap: false
    service: true
    ingress: true

# Deployment
image:
  repository: "" 
  tag: "v1"
  pullPolicy: IfNotPresent

replicaCount: 1
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

# Service
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Ingress
ingress:
  className: "alb"
  host: "shopnow.tranvix.click"
  path: "/"
  pathType: Prefix
  secretName: "shopnow-frontend-values"
  certificateArn: ""
  subnets: ""
  listenPorts: ""
  groupName: ""
  actionsSslRedirect: ""

# ConfigMap
configmap:
  data: {}
  # Example:
  # data:
  #   application.properties: |
  #     server.port=8080
  #     spring.datasource.url=jdbc:mysql://db-service:3306/mydb

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80