{{- if and .Values.global.enabledComponents.ingress .Values.global.enabledComponents.service }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.appName }}-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: {{ (index (secret "shopnow-frontend-values").data "certificateArn") | b64dec }}
    alb.ingress.kubernetes.io/subnets: {{ (index (secret "shopnow-frontend-values").data "subnets") | b64dec }}
    alb.ingress.kubernetes.io/listen-ports: {{ (index (secret "shopnow-frontend-values").data "listenPorts") | b64dec }}
    alb.ingress.kubernetes.io/group.name: {{ (index (secret "shopnow-frontend-values").data "groupName") | b64dec }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: {{ (index (secret "shopnow-frontend-values").data "actionsSslRedirect") | b64dec }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.global.appName }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
